apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 5001      # dışarı açılan port
      targetPort: 5001  # pod içindeki Flask app portu
      nodePort: 31001   # host makinedeki erişim portu


