apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1  # Pod say覺s覺n覺 1 olarak ayarlad覺k
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: merydinc/flask-llm-app:latest  
        ports:
        - containerPort: 5001
